org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=25
unityProjectPath=C:/Users/Admin/git/UnityGaussianSplatting/projects/GaussianExample-URP
unity.projectPath=C:/Users/Admin/git/UnityGaussianSplatting/projects/GaussianExample-URP
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=26
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.DefaultCompany.UnityGaussianSplatting
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.DefaultCompany.UnityGaussianSplatting
unity.agpVersion=9.0.0
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.5.4f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.5.4f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.5.4f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never